- name: DEPLOY AS£ 
  hosts: localhost
  connection: local
  gather_facts: no


  vars:

    uri_method: POST
    

  vars_files:
    - /mnt/c/Users/jason/Documents/Projects/Creds/creds.yml
    

  tasks: 

  - name: Create a JIRA issue
    uri:
      url: https://54.147.221.242/mgmt/shared/appsvcs/declare
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: "{{uri_method}}"
      body: "{{ lookup('file','mnt/c/Users/jason/Documents/Projects/Jason1/as3-dec.json') }}"
      force_basic_auth: yes
      status_code: 201
      body_format: json
      validate_certs: no

